#!/bin/bash

image=dot-qira
container=dot-qira-container

if [ ! "$(which docker)" ]; then
    echo "Error: Docker should be installed"
    exit
fi

if [ ! "$(docker images | grep $image)" ]; then
    echo "Building docker image"
    dir=`date +/tmp/qira.docker.%s`
    mkdir $dir
    file=$dir/Dockerfile
    echo "FROM ubuntu:16.04" > $file
    echo "RUN apt-get update && apt-get upgrade -y && apt-get install wget sudo -y" >> $file
    echo "RUN cd ~/ && wget -qO- https://github.com/BinaryAnalysisPlatform/qira/archive/v1.2.tar.gz | tar zx" >> $file
    echo "RUN cd ~/qira-1.2 && ./install.sh" >> $file
    docker build -t $image $dir
    rm -rf $dir
    exit
fi

if [ ! $# = 1 ]; then
    echo "Usage: $0 <binary>"
    exit
fi

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

real=$(realpath $1)
path=$(dirname $real)
name=$(basename $1)

echo Create container && docker run -p 3002:3002 -t -i --name $container -v $path:/root/shared $image qira /root/shared/$name
echo -n "Remove " && docker rm -f $container


