#!/bin/bash
#
# This script should be executed at .dots/
#

vimrc_src=vim/vimrc.vim
vimrc=$HOME/.vimrc

vimrc_local_src=vim/local.vim
vimrc_local=$HOME/.vimrc.local

vim_src=vim/vim
vim=$HOME/.vim

dots=$HOME/.dots


echo "@@@ Writing $vimrc"
echo "\" DO NOT EDIT THIS FILE, ADD YOUR CONFIGURATION TO $vimrc_local
source $dots/$vimrc_src
source $vimrc_local \" your local config should be here" > $vimrc

test -e $vimrc_local || {
    echo "@@@ Copying $vimrc_local_src to $vimrc_local"
    cp $vimrc_local_src $vimrc_local
}

echo "@@@ Copying $vim_src to $vim"
cp -R $vim_src $vim
